config/routes.rb
Rails.application.routes.draw do
	get 'recurring/new'

	#get 'recurring/create'
	post 'createbilling' => "recurring#create",as: 'createbilling'
	#get  'activatecharge/:id' => "recurring#activatecharge",as: 'activatecharge'
	get  'activatecharge/:id' => "home#activatecharge",as: 'activatecharge'
	get  'createnewrecurring' => "home#createnewrecurring",as: 'createnewrecurring'

	get 'recurring/update'

	get 'recurring/edit'

	#get 'recurring/destroy'
	delete 'destroyrecurring/:id/:shop_id' => "recurring#destroy",as: 'destroyrecurring'
	delete 'destroyrecurringhome/:id/:shop_id' => "home#destroy",as: 'destroyrecurringhome'

	#get 'recurring/show'
	get  'usage_charge/:id' => "recurring#show",as: 'usage_charge'

	get 'recurring/index'

	get 'settings/index'

	mount ShopifyApp::Engine, at: '/'
	get "auth/shopify/callback", to: 'home#callback'
	get "auth/shopify/login", to: 'home#index'
 	post 'setting' => "settings#create"

 	post 'webhookrequest' => "settings#webhookrequest"
 	get  'fetch_product' => "settings#fetch_product"
 	get  'check_shop_exist' => "settings#check_shop_exist"
 	get  'comingSoon' => "settings#comingSoon"

	post 'appUninstallWebHook' => "settings#appUninstallWebHook",as: 'appUninstallWebHook'

	post 'cartCreateWebHook' => "settings#cartCreateWebHook",as: 'cartCreateWebHook'

	post 'cartUpdateWebHook' => "settings#cartUpdateWebHook",as: 'cartUpdateWebHook'

	#routes for recurring path
	get  'decline_charge/:id' => "home#decline_charge",as: 'decline_charge'
	get  'all_orders/' => "home#all_orders",as: 'all_orders'

	root :to => 'home#index'
	#root :to => 'settings#comingSoon'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
#require 'nokogiri'

class HomeController < ShopifyApp::AuthenticatedController
  #after_action :allow_facebook_iframe
  #before_action :set_event, only: [:index]


  def index

   user_shop = session[:shopify_domain]
   @root_url = request.base_url
    ##code for access shopify information
    #vars = request.query_parameters
    #user_shop = vars[:shop]
    @shop_exist = Shop.where(:shopify_domain => user_shop).first

    unless @shop_exist.setting.present?

      #check if setting id is blank then install webhoks this check mentioned for first time when app installed
      @insured_product_id = nil
     
      ## shopify app uninstall webhook
      app_uininstall_webhook(request.base_url)
      app_cart_create_webhook(request.base_url)
      app_cart_update_webhook(request.base_url)
      ##end uninstall webhook

      ## shopify api for create webhook create order
      webhook_url = request.base_url+"/webhookrequest"
      webhook = ShopifyAPI::Webhook.create(:format => "json", :topic => "orders/create", :address =>webhook_url)
      ## end shopify api for create webhook

      ##create insured product
      @bundled_variant_id = create_insured_product(@root_url)
      ##end to create insured product

      ##create insured product
      @opt_in_variant_id = create_insured_product_opt_in(@root_url)
      ##end to create insured product
      

      #Save into settings also
      settingObj = Setting.new
      settingObj.shop_id = @shop_exist.id
      #settingObj.shopify_store_name = @shop_exist.shopify_domain
      settingObj.activation = 1
      settingObj.bundled_variant_id = @bundled_variant_id
      settingObj.opt_in_variant_id = @opt_in_variant_id
      settingObj.opt_in_value = 2
      settingObj.is_bundle = 1
      settingObj.save

      @shop_exist.setting = settingObj

      #call function to add script of shopify ajax api in theme.liquid file 
      add_script_in_theme_liquid(@root_url)
     
      #end to call function
    end
     

    @setting_id = ''
    if @shop_exist.setting.present?
      @setting_id = @shop_exist.setting.id

      add_customjs_in_cart_template(@root_url,@shop_exist.setting,@bundled_variant_id,@opt_in_variant_id)

    end

    #puts "====>"+@orders.inspect
  end #end action

  def callback
    user_shop = session[:shopify_domain]
    #puts "===hello callback==>"+user_shop
  	render :json => "hello"
  end

  def all_orders
    @orders = ShopifyAPI::Order.all
    user_shop = session[:shopify_domain]
    @shop_exist = Shop.where(:shopify_domain => user_shop).first
    puts "=====orders======="+@shop_exist.inspect
  end

  

  def destroy
    @shop_exist = Shop.where(:id => params[:shop_id]).first

    if @shop_exist.subscription.present?
      obj = Subscription.where(:id => @shop_exist.subscription.id).first
      t=obj.update_attributes(:status => 'decline')
      
    end

    @recurring_application_charge = ShopifyAPI::RecurringApplicationCharge.find(params[:id])

    @recurring_application_charge.cancel

    flash[:notice] = "Recurring application charge was cancelled successfully"

    redirect_to_correct_path(@recurring_application_charge,params[:shop_id])


  end

private
  
  def redirect_to_correct_path(recurring_application_charge,shop_id)
    if recurring_application_charge.try(:capped_amount)
      redirect_to decline_charge_path(shop_id)

      #redirect_to controller: 'home', action: 'index'
    else
      redirect_to recurring_application_charge_path
    end
  end

  def app_uininstall_webhook(url)
    # create webhook when app is uninstalled
    unless "https".in? url
      url.gsub! 'http', 'https'
    end

    webhook = {
        topic: 'app/uninstalled',
        address: "#{url}/appUninstallWebHook",
        format: 'json'}
    ShopifyAPI::Webhook.create(webhook)
  end 


  def app_cart_create_webhook(url)
    # create webhook when app is uninstalled
    unless "https".in? url
      url.gsub! 'http', 'https'
    end

    webhook = {
        topic: 'carts/create',
        address: "#{url}/cartCreateWebHook",
        format: 'json'}
    ShopifyAPI::Webhook.create(webhook)
  end 

  def app_cart_update_webhook(url)
    # create webhook when app is uninstalled
    unless "https".in? url
      url.gsub! 'http', 'https'
    end

    webhook = {
        topic: 'carts/update',
        address: "#{url}/cartUpdateWebHook",
        format: 'json'}
    ShopifyAPI::Webhook.create(webhook)
  end 

  def create_insured_product(url) 
    unless "https".in? url
      url.gsub! 'http', 'https'
    end


    images = []
    image = {}
    image["src"] = url+'/kedge.jpg'
    images << image

     new_product = ShopifyAPI::Product.new({
        title:                'Kedge Lost Stolen Damaged',
        body_html:            '<strong>Kedge is an independent,third party service that replace or refunds right away if the unexpected happens. Get Kedge 100% guaranteed coverage for lost, stolen, or damaged deliveries. Yes even for theft!</strong>',
        vendor:               'insurance',
        product_type:         'insurance',
        tags:                 'insurance,insured',
        images:               images
      })

      new_product.save
      #puts "=========variants bundled==========>"+new_product.variants.inspect
      #return new_product.id
      return new_product.variants.first.id
      
  end

  def create_insured_product_opt_in(url) 
    unless "https".in? url
      url.gsub! 'http', 'https'
    end


    images = []
    image = {}
    image["src"] = url+'/kedge.jpg'
    images << image

     new_product = ShopifyAPI::Product.new({
        title:                'Kedge Lost Stolen Damaged',
        body_html:            '<strong>Kedge is an independent,third party service that replace or refunds right away if the unexpected happens. Get Kedge 100% guaranteed coverage for lost, stolen, or damaged deliveries. Yes even for theft!</strong>',
        vendor:               'insurance',
        product_type:         'insurance',
        tags:                 'insurance,insured',
        images:               images
      })

      new_product.save

      new_product.variants << ShopifyAPI::Variant.new(
      :title => "Kedge Lost Stolen Damaged",
      :sku => "",
      :option1 => "Kedge Lost Stolen Damaged",
      :price => 0.01,
      :inventory_policy => "deny",
      :inventory_management => '',
      :inventory_quantity => 0,
      :position => 1
      )
      new_product.save
      #puts "=========variants opt in==========>"+new_product.variants.inspect
      #return new_product.id
      new_variant_id = new_product.variants[1].id
      return new_variant_id

  end


  def add_script_in_theme_liquid(url)
      asset_theme = ShopifyAPI::Asset.find('layout/theme.liquid') 
      backup_theme = asset_theme.value

      string_index_theme = asset_theme.value.index("{{ content_for_header")
      string_index_theme  = (string_index_theme.to_i)-1
      snippet_theme = '<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  {{ "api.jquery.js" | shopify_asset_url | script_tag }}'
      #puts "==yess==>"+snippet_theme

      unless "api.jquery.js".in? asset_theme.value
        backup_theme.insert string_index_theme, snippet_theme
        asset_theme.value = backup_theme
        theme_save=asset_theme.save
      end
    
  end

  def add_customjs_in_cart_template(url,settingObj,bundled_variant_id,opt_in_variant_id)
      asset_theme = ShopifyAPI::Asset.find('sections/cart-template.liquid') 
      backup_theme = asset_theme.value

      string_index_theme = asset_theme.value.index("{% schema")

      
      snippet_theme_src = url+"/assets/custom.js?shop="+settingObj.shop.shopify_domain

      snippet_theme = '<script data-id="boughtshopId" data-bundled_variant_id="'+bundled_variant_id.to_s+'" data-bundled_opt_in_id="'+opt_in_variant_id.to_s+'" data-requesturl="'+url+'" data-shop="'+settingObj.shop.shopify_domain+'" data-is_bundle="'+settingObj.is_bundle.to_s+'" data-is_opt_in="'+settingObj.is_opt_in.to_s+'" src="'+snippet_theme_src+'"></script>'

      unless "custom.js".in? asset_theme.value
        string_index_theme  = (string_index_theme.to_i)-1

        backup_theme.insert string_index_theme, snippet_theme
        asset_theme.value = backup_theme
        theme_save=asset_theme.save
      end
    
  end



  # def allow_facebook_iframe
  #   response.headers['X-Frame-Options'] = 'ALLOW-FROM https://slavatest3118.myshopify.com'
  # end

end

app/views/home/all_orders.html.erb
<div class="section custom-section">
  <div class= "col-md-3">
  </div>
  <div class="col-md-9">
    <p>
      <%=  link_to "Back to settings page", controller: "home", action: "index"%>
    </p>
  </div>
</div>
<h1>All orders</h1>

 <table style="width:100%">
	<tr>
		<th>S.No</th>
		<th>Order ID</th>
		<th>Order Number</th>
		<th>Subtotal Price</th>
		<th>Total Tax</th>
		<th>Total Price</th>
		<th>Gateway</th>
		<th>Line Items</th>
		<th>Customer</th>
		<th>Insured</th>
	</tr>
	<% i=1 %>
	<% @orders.each do |order| %>
	<% is_insured = 'No' %>
	  <tr>
	  	<td><%= i.to_s %>.</td>
	    <td><%= order.id %></td>
	    <td>#<%= order.order_number %></td>
	    <td><%= order.currency %>&nbsp<%= order.subtotal_price %></td>
	    <td><%= order.currency %>&nbsp<%= order.total_tax %></td>
	    <td><%= order.currency %>&nbsp<%= order.total_price %></td>
	    <td><%= order.gateway %></td>
	    <td>
	    	<% j=1 %>
	    	<% order.line_items.each do |line_item| %>

	    	<!-- check is insured -->
	    	<% if @shop_exist.setting.bundled_variant_id == line_item.variant_id %>
	    		<% is_insured = 'Yes Insured as bundled' %>
	    	<% end %>
	    	<% if @shop_exist.setting.opt_in_variant_id == line_item.variant_id %>
	    		<% is_insured = 'Yes Insured as opt in' %>
	    	<% end %>
	    	<!-- end check is insured -->


	    	<p>Item No.&nbsp;<%= j.to_s %></p>
	    	<p>Name:&nbsp;<%= line_item.title %></p>
	    	<p>Quantity:&nbsp;<%= line_item.quantity %></p>
	    	<p>Price:&nbsp;<%= order.currency %>&nbsp<%= line_item.price %></p>
	    	<% j = j+1 %>
	    	<% end %>

	    </td>
	    <td>
	    	
	    	<p>First Name:&nbsp;<%= order.customer.first_name.titleize %></p>
	    	<p>Last Name:&nbsp;<%= order.customer.last_name.titleize %></p>
	    	<% if order.customer.email.present? %>
	    		<p>Email:&nbsp;<%= order.customer.email %></p>
	    	<% end %>
	    	<p>Phone:&nbsp;<%= order.customer.phone %></p>
	    	<% if order.customer.default_address.present? %>
	    		<p>City:&nbsp;<%= order.customer.default_address.city.titleize %></p>
	    		<p>country:&nbsp;<%= order.customer.default_address.country %></p>
	    		<p>Zip:&nbsp;<%= order.customer.default_address.zip %></p>
	    	<% end %>
	    </td>
	    <td><%= is_insured %></td>
	  </tr>
	<% i = i+1 %>
	<% end %>
  
</table> 

app/views/home/decline_charge.html.erb
<script type="text/javascript">
  ShopifyApp.ready(function(){
    ShopifyApp.Bar.initialize({sectiontitle: "Usage Charge",
      icon: "<%= asset_path('favicon.png') %>"
    });
  });
</script>

<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<% if @recurring_application_charge.present? && @recurring_application_charge.try(:capped_amount) %>

<div class="section">
  <div class= "col-md-3">
    <h4>
      Recurring charge
    </h4>

    <p>
      Here you can see the terms of the recurring charge and the remaining balance.
    </p>
  </div>

  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="row">
           <div class="col-md-6">Total Usage Charges</div>
           <div class="col-md-6"><span class="pull-right">
            $<%= @recurring_application_charge.balance_used %> /
            $<%= @recurring_application_charge.capped_amount.to_f %>
           </span></div>
        </div>
       

      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-body">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Name</th>
              <th>Price</th>
              <th>Capped Amount</th>
              <th>Balance Remaining</th>
              <th>Billing On</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>
                <%= @recurring_application_charge.name %>
              </td>
              <td>
                $<%= @recurring_application_charge.price %>
              </td>
              <td>
                $<%= @recurring_application_charge.capped_amount.to_f %>
              </td>
              <td>
                $<%= @recurring_application_charge.balance_remaining %>
              </td>
              <td>
                <%= @recurring_application_charge.billing_on %>
              </td>
            </tr>
          </tbody>
        </table>

      </div>
    </div>
  </div>
</div>

<hr>

<div class="section">
  
  <div class="col-md-9">

    <% if @usage_charges.try!(:any?) %>
      <div class="panel panel-default">
        <div class="panel-body">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>Description</th>
                <th>Price</th>
                <th>Billing On</th>
              </tr>
            </thead>
            <tbody>
              <% @usage_charges.to_a.reverse.each do |charge| %>
                <tr>
                  <td>
                    <%= charge.description %>
                  </td>
                  <td>
                    $<%= charge.price %>
                  </td>
                  <td>
                    <%= charge.billing_on %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    <% end %>
  </div>
</div>
<div class="section custom-section">
  <div class= "col-md-3">
  </div>
  <div class="col-md-9">
    <p>
      <%= link_to 'Cancel charge', destroyrecurringhome_path(@recurring_application_charge,@shop_exist.id), method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure?" } %>

      <%=  link_to "Activate Recommendation Settings", controller: "home", action: "index"%>
     
    </p>
  </div>
</div>


<% else %>

<div class="section">
  <div class= "col-md-3">
    <h4>
      No Recurring charge Applied, to use the app!
    </h4>

    <p>
      
      <%=  link_to "Click here to create a new recurring charge with a capped amount.", createnewrecurring_path ,:target => "_blank"%>
    </p>
  </div>

  
</div>

<% end %>

app/views/home/index.html.erb
<div class="section">
    <div class="section-summary">
        <h1>View All Orders</h1>
    </div>
    <div class="section-content">
        <div class="section-row">
            <div class="section-cell">
                <div>
                    <div>
                        <%=  link_to "Click here to see all orders", all_orders_path() %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<% form_url = "#{@root_url}/setting?embed=yes" %>
<%= form_tag(form_url, method: "post",  :onsubmit => 'return validateForm()', :target => 'app-iframe') do %>
<input type="hidden" name="setting[shop_id]" value="<%= @shop_exist.id %>">
<input type="hidden" name="setting[id]" value="<%= @setting_id %>">

<div class="section">
   <div class="section-summary">
      <h1>Insurance Coverage Settings</h1>
      <p>Please select one of the setting atleast by click one of the checkbox.</p>
   </div>
   <div class="section-content">
    
      <div class="section-row">
      </div>

      <div class="section-cell">
        <label>Bundled Settings</label>
        <input type="hidden" name="setting[is_bundle]" value="0">
             <input type="checkbox" id="automatic_recommendations" name="setting[is_bundle]" value="1" <%= ( @shop_exist.setting.present? && @shop_exist.setting.is_bundle?) ? 'checked':'' %>  class="set_check">
        <label class="checkbox-label" for="showAutomaticRecommendations">
            Show automatic recommendations based on previous sales
        </label>
    </div>

    <div class="section-cell">
      <label>Opt-in / Opt-out</label>
      <input type="hidden" name="setting[is_opt_in]" value="0">
           <input type="checkbox" id="automatic_recommendations" name="setting[is_opt_in]" value="1" <%= ( @shop_exist.setting.present? && @shop_exist.setting.is_opt_in?) ? 'checked':'' %>  class="set_check">
      <label class="checkbox-label" for="showAutomaticRecommendations">
          Show automatic recommendations based on previous sales
      </label>
  </div>

   </div>
</div>
 <div class="section">
        <div class="section-content submit">
           <span style="color:red;display:none;" id="span_err"></span>

        </div>
    </div>
<div class="section">
   <div class="section-content submit">
      <!-- <a href="https://<%= @shop_exist.shopify_domain%>/admin/apps" class="cancel_btn">Back</a> -->
      <input id="submitButton"  type="submit" class="btn" value="Save">
      <input id="submit_btn" style="display:none;" type="button" class="btn" value="Loading...">
   </div>
</div>
<% end %>
<div>
</div>
<script>
   function validateForm() {
       var x = $('input[class="set_check"]:checked').length;
       if (x > 1) {
           $("#span_err").text('You can check only one checkbox at one time!');
           $("#span_err").show().delay(5000).fadeOut();
           return false;
       } else if(x == 0) {
           $("#span_err").text('Please check at least one checkbox!');
           $("#span_err").show().delay(5000).fadeOut();
           return false;
       } else {
           $("#submitButton").hide();
           $("#submit_btn").show();
       }
   } 
</script>