config/routes.rb
Rails.application.routes.draw do
	get 'recurring/new'

	#get 'recurring/create'
	post 'createbilling' => "recurring#create",as: 'createbilling'
	#get  'activatecharge/:id' => "recurring#activatecharge",as: 'activatecharge'
	get  'activatecharge/:id' => "home#activatecharge",as: 'activatecharge'
	get  'createnewrecurring' => "home#createnewrecurring",as: 'createnewrecurring'

	get 'recurring/update'

	get 'recurring/edit'

	#get 'recurring/destroy'
	delete 'destroyrecurring/:id/:shop_id' => "recurring#destroy",as: 'destroyrecurring'
	delete 'destroyrecurringhome/:id/:shop_id' => "home#destroy",as: 'destroyrecurringhome'

	#get 'recurring/show'
	get  'usage_charge/:id' => "recurring#show",as: 'usage_charge'

	get 'recurring/index'

	get 'settings/index'

	mount ShopifyApp::Engine, at: '/'
	get "auth/shopify/callback", to: 'home#callback'
	get "auth/shopify/login", to: 'home#index'
 	post 'setting' => "settings#create"

 	post 'webhookrequest' => "settings#webhookrequest"
 	get  'fetch_product' => "settings#fetch_product"
 	get  'check_shop_exist' => "settings#check_shop_exist"
 	get  'comingSoon' => "settings#comingSoon"

	post 'appUninstallWebHook' => "settings#appUninstallWebHook",as: 'appUninstallWebHook'

	post 'cartCreateWebHook' => "settings#cartCreateWebHook",as: 'cartCreateWebHook'

	post 'cartUpdateWebHook' => "settings#cartUpdateWebHook",as: 'cartUpdateWebHook'

	#routes for recurring path
	get  'decline_charge/:id' => "home#decline_charge",as: 'decline_charge'
	get  'all_orders/' => "home#all_orders",as: 'all_orders'

	root :to => 'home#index'
	#root :to => 'settings#comingSoon'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/recurring_controller.rb
class RecurringController < ApplicationController
   skip_before_action :verify_authenticity_token, :only => [:create]
   #before_action :load_current_recurring_charge

  def new
  end

  def create
    @root_url = request.base_url
    @shop_exist = Shop.where(:id => params[:shop_id]).first
    #start sessiom
    check_session(@shop_exist.id)

    #check previous subscription
    @recurring_application_charge = ShopifyAPI::RecurringApplicationCharge.current
    @recurring_application_charge.try!(:cancel)

    @recurring_application_charge = ShopifyAPI::RecurringApplicationCharge.new(
            name: "Shopify Product Insurance",
            price: 9.99,
            return_url:  @root_url+"/activatecharge/"+params[:shop_id],
            test: true,
            trial_days: 7,
            capped_amount: 100,
            terms: "$9.99 for every month")

    if @recurring_application_charge.save
      #@fullpage_redirect_to @recurring_application_charge.confirmation_url

      render :json => {:status => 'success',:url => @recurring_application_charge.confirmation_url}
    else
      #flash[:danger] = @recurring_application_charge.errors.full_messages.first.to_s.capitalize
      #redirect_to_correct_path(@recurring_application_charge)
       render :json => {:status => 'error',:message => @recurring_application_charge.errors.full_messages.first.to_s.capitalize}
    end
    
    #render :json => params

  end

  def activatecharge

    @shop_exist = Shop.where(:id => params[:id]).first
    #start sessiom
    check_session(@shop_exist.id)

    vars = request.query_parameters
    charge_id = (vars[:charge_id].present?) ? vars[:charge_id] : ''

    @recurring_application_charge = ShopifyAPI::RecurringApplicationCharge.find(charge_id)

    if @recurring_application_charge.status == 'accepted'
      @recurring_application_charge.activate
    end

    #create_order_webhook
    redirect_to_correct_path(@recurring_application_charge,params[:id])
    #redirect bulk_edit_url

    #render :json => params
  end

  def update
  end 

  def edit
  end

  def destroy
     @shop_exist = Shop.where(:id => params[:shop_id]).first
    #start sessiom
    check_session(@shop_exist.id)
    @recurring_application_charge = ShopifyAPI::RecurringApplicationCharge.find(params[:id])

    @recurring_application_charge.cancel

    flash[:success] = "Recurring application charge was cancelled successfully"

    redirect_to_correct_path(@recurring_application_charge,params[:shop_id])
  end

  def show
    @shop_exist = Shop.where(:id => params[:id]).first
    #start sessiom
    check_session(@shop_exist.id)

    @recurring_application_charge = ShopifyAPI::RecurringApplicationCharge.current
    @usage_charges = @recurring_application_charge.usage_charges if @recurring_application_charge.try(:capped_amount)
  end

  def index
  end

private

  def load_current_recurring_charge
    @recurring_application_charge = ShopifyAPI::RecurringApplicationCharge.current
  end

  def check_session(shop_id)
    session = ShopifyAPI::Session.new( @shop_exist.shopify_domain, @shop_exist.shopify_token)
    ShopifyAPI::Base.activate_session(session)
  end

  def recurring_application_charge_params
    params.require(:recurring_application_charge).permit(
      :name,
      :price,
      :capped_amount,
      :terms,
      :trial_days
    )
  end

  def redirect_to_correct_path(recurring_application_charge,shop_id)
    if recurring_application_charge.try(:capped_amount)
      #puts "====in if===>"
      redirect_to usage_charge_path(shop_id)
    else
      #puts "========in else======>"
      redirect_to recurring_application_charge_path
    end
  end


end

app/helpers/recurring_helper.rb
module RecurringHelper
end

app/views/recurring/create.html.erb
<h1>Recurring#create</h1>
<p>Find me in app/views/recurring/create.html.erb</p>

app/views/recurring/destroy.html.erb
<h1>Recurring#destroy</h1>
<p>Find me in app/views/recurring/destroy.html.erb</p>

app/views/recurring/edit.html.erb
<h1>Recurring#edit</h1>
<p>Find me in app/views/recurring/edit.html.erb</p>

app/views/recurring/index.html.erb
<h1>Recurring#index</h1>
<p>Find me in app/views/recurring/index.html.erb</p>

app/views/recurring/new.html.erb
<h1>Recurring#new</h1>
<p>Find me in app/views/recurring/new.html.erb</p>

app/views/recurring/show.html.erb
<script type="text/javascript">
  ShopifyApp.ready(function(){
    ShopifyApp.Bar.initialize({
      title: "Usage Charge",
      icon: "<%= asset_path('favicon.png') %>"
    });
  });
</script>

<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<% if @recurring_application_charge.present? && @recurring_application_charge.try(:capped_amount) %>

<div class="section">
  <div class= "col-md-3">
    <h4>
      Recurring charge
    </h4>

    <p>
      Here you can see the terms of the recurring charge and the remaining balance.
    </p>
  </div>

  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="row">
           <div class="col-md-6">Total Usage Charges</div>
           <div class="col-md-6"><span class="pull-right">
            $<%= @recurring_application_charge.balance_used %> /
            $<%= @recurring_application_charge.capped_amount.to_f %>
           </span></div>
        </div>
        <div class="progress progress-usage" define="{ percentage: <%= balance_used_percentage(@recurring_application_charge) %> }">
          <div class="progress-bar" role="progressbar" aria-valuenow="<%= balance_used_percentage(@recurring_application_charge) %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= balance_used_percentage(@recurring_application_charge) %>%" bind-class="{ 'progress-bar-warning': (percentage > 60 && percentage <= 80), 'progress-bar-danger': percentage  > 80  }">
          </div>
        </div>

      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-body">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Name</th>
              <th>Price</th>
              <th>Capped Amount</th>
              <th>Balance Remaining</th>
              <th>Billing On</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>
                <%= @recurring_application_charge.name %>
              </td>
              <td>
                $<%= @recurring_application_charge.price %>
              </td>
              <td>
                $<%= @recurring_application_charge.capped_amount.to_f %>
              </td>
              <td>
                $<%= @recurring_application_charge.balance_remaining %>
              </td>
              <td>
                <%= @recurring_application_charge.billing_on %>
              </td>
            </tr>
          </tbody>
        </table>

      </div>
    </div>
  </div>
</div>

<hr>

<div class="section">
  <div class= "col-md-3">
    <h4>
      Usage Charge
    </h4>
    <p>
      Create new usage charges
    </p>
  </div>

  <div class="col-md-9">

    <% if @usage_charges.try!(:any?) %>
      <div class="panel panel-default">
        <div class="panel-body">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>Description</th>
                <th>Price</th>
                <th>Billing On</th>
              </tr>
            </thead>
            <tbody>
              <% @usage_charges.to_a.reverse.each do |charge| %>
                <tr>
                  <td>
                    <%= charge.description %>
                  </td>
                  <td>
                    $<%= charge.price %>
                  </td>
                  <td>
                    <%= charge.billing_on %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    <% end %>
  </div>
</div>

<hr />

<div class="section">
  <div class= "col-md-3">
  </div>
  <div class="col-md-9">
    <p>
      <%= link_to 'Cancel charge', destroyrecurring_path(@recurring_application_charge,@shop_exist.id), method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure?" } %>
      
    </p>
  </div>
</div>


<% else %>

<div class="section">
  <div class= "col-md-3">
    <h4>
      No Recurring charge Applied
    </h4>

    <p>
      Create a new recurring charge with a capped amount.
    </p>
  </div>

  
</div>

<% end %>

app/views/recurring/update.html.erb
<h1>Recurring#update</h1>
<p>Find me in app/views/recurring/update.html.erb</p>